spring:
  #h2:
   #console:
    #enabled: true
    #path: /h2-console
  #jpa:
    #show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/utnPhones
    username: root
    password: root
  jpa:
    hibernate:
      generate-ddl: false